version: "3.9"

volumes:
  octoprint:
  code-server:

services:
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --monitor-only

  traefik:
    image: traefik:2.3
    restart: always
    command:
      - --providers.docker
      - --providers.docker.exposedByDefault=false
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./.htdigest:/.htdigest
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.auth.digestauth.usersfile=/.htdigest
      - traefik.http.middlewares.auth.digestauth.headerField=X-Auth-User

  octoprint:
    build:
      context: .
      dockerfile: octoprint.Dockerfile
    restart: always
    device_cgroup_rules:
      - c 188:* rmw
    volumes:
      - ./data/octoprint:/octoprint
      - /dev:/dev
    labels:
      - traefik.enable=true
      - traefik.http.routers.octoprint.rule=PathPrefix(`/octoprint`)
      - traefik.http.middlewares.octoprint-stripprefix.stripprefix.prefixes=/octoprint
      - traefik.http.middlewares.octoprint-customrequestheaders.headers.customrequestheaders.X-Script-Name=/octoprint
      - traefik.http.routers.octoprint.middlewares=auth,octoprint-customrequestheaders,octoprint-stripprefix
