volumes:
  octoprint:
  code-server:

services:
  traefik:
    image: traefik:2.8
    restart: always
    command:
      - --providers.docker
      - --providers.docker.exposedByDefault=false
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./.htaccess:/.htaccess
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.auth.basicauth.usersfile=/.htaccess

  octoprint:
    build:
      context: .
      dockerfile: octoprint.Dockerfile
    restart: always
    device_cgroup_rules:
      - c 188:* rmw
    volumes:
      - octoprint:/octoprint
      - /dev:/dev
    labels:
      - traefik.enable=true
      - traefik.http.routers.octoprint.rule=PathPrefix(`/octoprint`)
      - traefik.http.middlewares.octoprint-stripprefix.stripprefix.prefixes=/octoprint
      - traefik.http.middlewares.octoprint-customrequestheaders.headers.customrequestheaders.X-Script-Name=/octoprint
      - traefik.http.routers.octoprint.middlewares=auth,octoprint-customrequestheaders,octoprint-stripprefix

  octoprint-config:
    image: linuxserver/code-server
    restart: always
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Rome
    volumes:
      - octoprint:/octoprint
      - code-server:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.octoprint-config.rule=PathPrefix(`/octoprint/config`)
      - traefik.http.middlewares.octoprint-config-stripprefix.stripprefix.prefixes=/octoprint/config
      - traefik.http.middlewares.octoprint-config-redirect.redirectregex.regex=^(.+/octoprint/config)/?$$
      - traefik.http.middlewares.octoprint-config-redirect.redirectregex.replacement=$$1/
      - traefik.http.routers.octoprint-config.middlewares=auth,octoprint-config-redirect,octoprint-config-stripprefix
