version: "3.9"

volumes:
  octoprint:
  letsencrypt:

services:
  traefik:
    build:
      dockerfile: Dockerfile.traefik
      context: .
    command:
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--certificatesresolvers.acme-resolver.acme.tlschallenge=true"
      - "--certificatesresolvers.acme-resolver.acme.email=lnzmrr@gmail.com"
      - "--certificatesresolvers.acme-resolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  octoprint:
    image: "octoprint/octoprint:minimal"
    build:
      dockerfile: Dockerfile.octoprint
      context: .
    volumes:
      - "octoprint:/octoprint"
    labels:
      - "traefik.http.routers.octoprint.rule=Host(`murar8.ddns.net`) && PathPrefix(`/octoprint`)"
      - "traefik.http.routers.octoprint.tls=true"
      - "traefik.http.routers.octoprint.tls.certresolver=acme-resolver"
      - "traefik.http.routers.octoprint.middlewares=octoprint-customrequestheaders,octoprint-stripprefix"
      - "traefik.http.middlewares.octoprint-stripprefix.stripprefix.prefixes=/octoprint"
      - "traefik.http.middlewares.octoprint-customrequestheaders.headers.customrequestheaders.X-Script-Name=/octoprint"
      - "traefik.http.middlewares.octoprint-customrequestheaders.headers.customrequestheaders.X-Forwarded-Proto=https"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
