version: "3.9"

volumes:
  octoprint:
  acme:

services:
  traefik:
    image: traefik:2.3
    command:
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--certificatesresolvers.acme-resolver.acme.tlschallenge=true"
      - "--certificatesresolvers.acme-resolver.acme.email=lnzmrr@gmail.com"
      - "--certificatesresolvers.acme-resolver.acme.storage=/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - acme:/acme.json"

  # nginx:
  #   image: nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   labels:
  #     - traefik.http.routers.whoami.rule=Host(`murar8.ddns.net`)
  #     - traefik.http.routers.whoami.tls=true
  #     - traefik.http.routers.whoami.tls.certresolver=acme-resolver

  octoprint:
    # image: traefik/whoami
    image: octoprint/octoprint:minimal
    volumes:
      - octoprint:/octoprint
    labels:
      - "traefik.http.routers.octoprint.rule=Host(`murar8.ddns.net`) && PathPrefix(`/octoprint`)"
      - "traefik.http.routers.octoprint.tls=true"
      - "traefik.http.routers.octoprint.tls.certresolver=acme-resolver"
      - "traefik.http.routers.octoprint.middlewares=octoprint-customrequestheaders,octoprint-stripprefix"
      - "traefik.http.middlewares.octoprint-stripprefix.stripprefix.prefixes=/octoprint"
      - "traefik.http.middlewares.octoprint-customrequestheaders.headers.customrequestheaders.X-Script-Name=/octoprint"
      - "traefik.http.middlewares.octoprint-customrequestheaders.headers.customrequestheaders.X-Forwarded-Proto=https"
